//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Ironworks Home Page</summary>
	[PublishedContentModel("IronworksHomePage")]
	public partial class IronworksHomePage : IronworksBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "IronworksHomePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public IronworksHomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<IronworksHomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main Tag Line
		///</summary>
		[ImplementPropertyType("mainTagLine")]
		public string MainTagLine
		{
			get { return this.GetPropertyValue<string>("mainTagLine"); }
		}

		///<summary>
		/// Safety Content
		///</summary>
		[ImplementPropertyType("safetyContent")]
		public IHtmlString SafetyContent
		{
			get { return this.GetPropertyValue<IHtmlString>("safetyContent"); }
		}

		///<summary>
		/// Secondary Tag Line
		///</summary>
		[ImplementPropertyType("secondaryTagLine")]
		public string SecondaryTagLine
		{
			get { return this.GetPropertyValue<string>("secondaryTagLine"); }
		}

		///<summary>
		/// Services Content
		///</summary>
		[ImplementPropertyType("servicesContent")]
		public IHtmlString ServicesContent
		{
			get { return this.GetPropertyValue<IHtmlString>("servicesContent"); }
		}
	}
}
